# Generated by Django 3.2.6 on 2021-10-21 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=128, verbose_name='Прізвище')),
                ('name', models.CharField(max_length=128, verbose_name="Ім'я")),
                ('fatname', models.CharField(max_length=128, verbose_name='По-батькові')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='Номер телефону')),
                ('email', models.EmailField(blank=True, max_length=128, null=True, verbose_name='Електронна пошта')),
                ('tgid', models.CharField(blank=True, default='default', max_length=32, null=True, verbose_name='Телеграм id')),
                ('is_parent', models.BooleanField(default=False, verbose_name='Ця особа є платником студента')),
            ],
            options={
                'verbose_name': 'Клієнт',
                'verbose_name_plural': 'Клієнти',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Назва курсу')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курси',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=128, verbose_name='Прізвище')),
                ('name', models.CharField(max_length=128, verbose_name="Ім'я")),
                ('fatname', models.CharField(max_length=128, verbose_name='По-батькові')),
                ('id_code', models.PositiveIntegerField(verbose_name='ЄДРПОУ')),
                ('bank', models.CharField(max_length=128, verbose_name='Назва банку/філії')),
                ('bank_account', models.CharField(max_length=256, verbose_name='Номер рахунку')),
            ],
            options={
                'verbose_name': 'ФОП',
                'verbose_name_plural': 'ФОПи',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=128, verbose_name='Прізвище')),
                ('name', models.CharField(max_length=128, verbose_name="Ім'я")),
                ('fatname', models.CharField(max_length=128, verbose_name='По-батькові')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенти',
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.PositiveIntegerField(verbose_name='Сума')),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.client', verbose_name='Клієнт')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.course', verbose_name='Напрям навчання')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.employer', verbose_name='ФОП')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
            },
        ),
    ]
